reintroduce input capture filter
am32-firmware/AM32 pull request #77
Opened 2024-08-29 11:28 UTC by AlkaMotors

2024-08-31 09:38 UTC, tridge requested changes
great to see the input filtering!
some of the new targets don't build, for example AM32_FLYWOO_F4A_F421 fails with:
```
Mcu/f421/Src/phaseouts.c: In function 'comStep':
Mcu/f421/Src/phaseouts.c:332:24: error: 'PHASE_C_COMP' undeclared (first use in this function)
  332 |         CMP->ctrlsts = PHASE_C_COMP;
      |                        ^~~~~~~~~~~~
Mcu/f421/Src/phaseouts.c:339:24: error: 'PHASE_A_COMP' undeclared (first use in this function)
  339 |         CMP->ctrlsts = PHASE_A_COMP;
      |                        ^~~~~~~~~~~~
Mcu/f421/Src/phaseouts.c:346:24: error: 'PHASE_B_COMP' undeclared (first use in this function)
  346 |         CMP->ctrlsts = PHASE_B_COMP;
      |                        ^~~~~~~~~~~~
```
you can see this in the CI build tests
also, a minor thing, it is a good idea to use a branch other than 'main' for PRs, for example 'pr-input-filter' would be good, makes it easier to track

2024-09-07 04:54 UTC, AlkaMotors commented
Whats wrong with these targets? It builds in Keil. The hardware group is defined.

2024-09-08 21:30 UTC, tridge commented
> Whats wrong with these targets?

I've put a branch here with fixes to the issues:
https://github.com/tridge/AM32/commits/alka-main-fixes/
one problem was an incorrect file name, another was due to the 12 character limit

2024-09-10 23:47 UTC, tridge approved these changes

2024-09-10 23:49 UTC, merged